# Oral History as Data (OHD) - a Lib-STATIC Tool
# https://github.com/uidaholib/oral-history-as-data


##########
# URL settings 
#
# url is your gh-pages base, following the pattern: username.github.io
url: https://deck4106.github.io
# baseurl is your github repository's name prefixed with a /
baseurl: /kourtnie_test_repository-
# repository is the github repository's full url
repository: https://github.com/deck4106/kourtnie_test_repository-


##########
# Site settings
#
# title of site appears in banner
title: Kourtnie's First Repository
# tagline appears in banner
tagline: she is the best
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "kourtnie's little site"


####### Leave the Below As Is ########

# Jekyll collections settings
collections:
  transcripts:
    output: true
    permalink: /:collection/:name
  howto:
    output: true
    permalink: /:collection/:name
# defaults
defaults:
  - scope:
      type: transcripts
    values:
      layout: transcript
  - scope:
      type: howto
    values:
      layout: howto

# Build settings
markdown: kramdown

